using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Text;

namespace I18n.Json.SourceGen
{
    [Generator]
    public class HelloWorldGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("GeneratedConstants.g.cs", @"
// <auto-generated/>
namespace Generated
{
    public static class GeneratedConstants
    {
        public static readonly string Hello = ""Hello from Source Generator!"";
    }
}
");
            });
        }
    }
}
