using Microsoft.CodeAnalysis;
using System.IO;
using System.Linq;

namespace I18n.Json.SourceGen;

[Generator]
public class LocaleGenerator : IIncrementalGenerator
{
    public class LocaleFileResult(string Path, string Content, string Error = null);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        Logger.Print("Initializing LocaleGenerator...");

        var config = ConfigReader.Create(context);

        var localeFiles = context.AdditionalTextsProvider
            .Combine(config)
            .Select((pair, ct) =>
            {
                var file = pair.Left;
                var config = pair.Right;

                Logger.Print($"file = {file.ToString()}");


                bool isMatched = config.LocalePaths.Any(p =>
                    file.Path.Contains(p.Replace("/", Path.DirectorySeparatorChar.ToString())));

                if (isMatched && file.Path.EndsWith(".json"))
                {
                    var content = file.GetText(ct)?.ToString();
                    if (string.IsNullOrWhiteSpace(content))
                    {
                        Logger.Print(file.Path + "[empty]");
                        return null;
                    }

                    Logger.Print(file.Path);
                    return file.Path;
                }

                Logger.Print("null path");
                return null;
            })
            .Where(x => x != null);


        //var localeFilesProvider = context.AdditionalTextsProvider
        //    .Combine(configProvider)
        //    .Select((pair, ct) =>
        //    {
        //        var file = pair.Left;
        //        var config = pair.Right;

        //        bool isMatched = config.LocalePaths.Any(p =>
        //            file.Path.Contains(p.Replace("/", Path.DirectorySeparatorChar.ToString())));

        //        if (isMatched && file.Path.EndsWith(".json"))
        //        {
        //            var content = file.GetText(ct)?.ToString();
        //            if (string.IsNullOrWhiteSpace(content))
        //                return new LocaleFileResult(file.Path, null, "File is empty");

        //            return new LocaleFileResult(file.Path, content);
        //        }

        //        return null;
        //    })
        //    .Where(x => x != null);

        //var localeData = context.AdditionalTextsProvider
        //    .Combine(configProvider)
        //    .SelectMany((pair, ct) => GetLocaleData(pair.Left, pair.Right, ct));

        //var combinedProvider = localeData.Collect().Combine(configProvider);

        //context.RegisterSourceOutput(combinedProvider, (spc, source) =>
        //{
        //    var (keys, config) = source;

        //    var sb = new StringBuilder();

        //    sb.AppendLine("// <auto-generated/>");
        //    sb.AppendLine($"namespace {config.Namespace}");
        //    sb.AppendLine("{");
        //    sb.AppendLine($"    public static class {config.LocaleFileNameWithoutExtension}");
        //    sb.AppendLine("    {");

        //    // Если ключи есть — генерируем их
        //    if (!keys.IsDefaultOrEmpty)
        //    {
        //        foreach (var (key, value) in keys)
        //        {
        //            string safeName = CleanIdentifier(key);
        //            string safeValue = value.Replace("\"", "\\\"");
        //            sb.AppendLine($"        public static readonly string {safeName} = \"{safeValue}\";");
        //        }
        //    }
        //    else
        //    {
        //        // Можно оставить комментарий для дебага, почему класс пустой
        //        sb.AppendLine("        // No keys found in locale file or file is empty.");
        //    }

        //    sb.AppendLine("    }");
        //    sb.AppendLine("}");

        //    // Файл будет создан в любом случае
        //    spc.AddSource("GeneratedConstants.g.cs", sb.ToString());
        //});


        context.RegisterSourceOutput(localeFiles, (spc, source) =>
        {
            Logger.FlushLogs(spc);
        });
    }

    //private ImmutableArray<(string Key, string Value)> GetLocaleData(
    //    AdditionalText file,
    //    Config config,
    //    CancellationToken ct)
    //{
    //    var fileName = Path.GetFileName(file.Path);
    //    if (!fileName.Equals(config.LocaleFileName, StringComparison.OrdinalIgnoreCase))
    //    {
    //        return ImmutableArray<(string Key, string Value)>.Empty;
    //    }

    //    var text = file.GetText(ct)?.ToString();
    //    if (string.IsNullOrWhiteSpace(text))
    //    {
    //        return ImmutableArray<(string Key, string Value)>.Empty;
    //    }

    //    try
    //    {
    //        using var doc = JsonDocument.Parse(text!);
    //        var builder = ImmutableArray.CreateBuilder<(string, string)>();

    //        foreach (var prop in doc.RootElement.EnumerateObject())
    //        {
    //            builder.Add((prop.Name, prop.Value.GetString() ?? string.Empty));
    //        }

    //        return builder.ToImmutable();
    //    }
    //    catch
    //    {
    //        return ImmutableArray<(string Key, string Value)>.Empty;
    //    }
    //}

    private static string CleanIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return "Unknown";

        var chars = name.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            if (!char.IsLetterOrDigit(chars[i]))
            {
                chars[i] = '_';
            }
        }

        var clean = new string(chars);

        return char.IsDigit(clean[0]) ? "_" + clean : clean;
    }
}
